import type {
  GeneralSkill,
  InterviewAnswerGuidance,
  InterviewQuestion,
  ReportData,
} from "@/types/report";

type GeneralSkillId = "research" | "practice" | "communication" | "international" | "professionalism";

type GeneralSkillAssessment = {
  score: number | null;
  requiredScore: number;
  weight: number;
  jdMatchBasis: string;
  experienceEvidence: string | null;
};

const mockAnswerGuidance: Record<string, InterviewAnswerGuidance> = {
  "ip-q1": {
    background: "平台经济商标保护相关研究项目。",
    personalAction: "围绕平台商标侵权责任检索法规及代表性案例，并比较平台治理规则与裁判观点。",
    legalReasoning: "研究内容涉及商标侵权责任与平台治理规则。",
    output: "形成 12,000 字研究报告。",
    missingFacts: ["本人负责的具体报告部分", "研究成果最终用途"],
  },
  "ip-q2": {
    background: "知识产权案例分析项目。",
    personalAction: "比较侵权构成、抗辩理由与损害赔偿相关判例。",
    legalReasoning: "围绕侵权构成、抗辩与赔偿规则开展要件分析。",
    missingFacts: ["案例分析形成的具体材料", "个人负责范围", "成果用途"],
  },
  "ip-q3": {
    background: "平台经济商标保护研究与知识产权案例分析项目。",
    legalReasoning: "现有研究覆盖商标保护、平台侵权治理及风险识别。",
    missingFacts: ["对企业知识产权价值的个人理解", "研究结论如何转化为企业管理建议"],
  },
  "ip-q4": {
    background: "知识产权案例分析项目。",
    personalAction: "完成侵权构成、抗辩理由与损害赔偿判例比较。",
    legalReasoning: "现有材料能够支持侵权要件分析，但未体现实际处置流程。",
    missingFacts: ["是否做过证据固定", "是否参与平台投诉或争议处置", "形成的处置建议"],
  },
  "ip-q5": {
    background: "合同审查课程项目。",
    personalAction: "完成服务合同条款分析。",
    missingFacts: ["具体审查条款", "识别的风险", "形成的修改意见", "是否接触知识产权合同"],
  },
  "ip-q6": {
    missingFacts: ["真实跨部门沟通经历", "当时的分歧或目标", "本人采取的沟通动作", "最终结果"],
  },
  "ip-q7": {
    background: "平台经济商标保护研究、知识产权案例分析项目及知识产权法专题课程。",
    missingFacts: ["选择企业知识产权法务的真实动机", "与诉讼或代理方向相比的岗位理解"],
  },
  "ip-q8": {
    background: "CET-6 532 分，并有英文知识产权论文阅读经历。",
    personalAction: "阅读英文知识产权论文。",
    missingFacts: ["是否处理过英文许可文件", "阅读时提取的具体法律信息", "复核方法与产出"],
  },
};

function interviewQuestion(
  id: string,
  type: InterviewQuestion["type"],
  ...args:
    | [InterviewQuestion["probability"], string, string[], string, string[], InterviewAnswerGuidance?]
    | [string, string[], string, string[], InterviewAnswerGuidance?]
): InterviewQuestion {
  const hasProbability = args[0] === "high" || args[0] === "medium";
  const probability: InterviewQuestion["probability"] = hasProbability
    ? (args[0] as InterviewQuestion["probability"])
    : "medium";
  const offset = hasProbability ? 1 : 0;
  const question = args[offset] as string;
  const focusPoints = args[offset + 1] as string[];
  const suggestedExperience = args[offset + 2] as string;
  const followUpQuestions = args[offset + 3] as string[];
  const answerGuidance =
    (args[offset + 4] as InterviewAnswerGuidance | undefined) ??
    mockAnswerGuidance[id] ?? {
      missingFacts: ["对应的真实经历背景", "本人具体动作", "法律判断过程", "工作产出", "最终用途或结果"],
    };

  return {
    id,
    type,
    probability,
    question,
    focusPoints,
    suggestedExperience,
    sourceExperience: suggestedExperience,
    testedSkill: focusPoints[0] ?? "岗位核心能力",
    professionalExtension: focusPoints.slice(1).join("、") || "结合岗位专业场景展开",
    followUpQuestions,
    answerGuidance,
  };
}

const generalSkillCatalog: Record<
  GeneralSkillId,
  Pick<GeneralSkill, "id" | "name" | "description" | "subSkills">
> = {
  research: {
    id: "legal-research-analysis",
    name: "法律研究与分析能力",
    description: "发现、分析和解决法律问题的能力。",
    subSkills: ["法律检索", "案例研究", "法规政策分析", "法律论证"],
  },
  practice: {
    id: "legal-practice-execution",
    name: "法律实务执行能力",
    description: "完成具体法律工作并形成专业交付的能力。",
    subSkills: ["合同审核", "尽职调查", "法律文书", "案件支持"],
  },
  communication: {
    id: "legal-communication",
    name: "法律表达与沟通能力",
    description: "准确表达法律判断并通过协作推动事项进展的能力。",
    subSkills: ["客户沟通", "团队协作", "观点表达"],
  },
  international: {
    id: "international-language",
    name: "外语与涉外能力",
    description: "处理外语法律材料与跨境法律事务的能力。",
    subSkills: ["英文法律文件", "英文写作", "跨境沟通"],
  },
  professionalism: {
    id: "professional-execution",
    name: "职业素养与成长能力",
    description: "以可靠、细致和持续学习的方式完成法律工作的能力。",
    subSkills: ["责任意识", "学习能力", "工作细致程度"],
  },
};

function createGeneralSkills(
  assessments: Record<GeneralSkillId, GeneralSkillAssessment>,
): GeneralSkill[] {
  return (Object.keys(generalSkillCatalog) as GeneralSkillId[]).map((id) => {
    const assessment = assessments[id];
    return {
      ...generalSkillCatalog[id],
      jdRequirement: assessment.requiredScore,
      resumeEvidenceScore: assessment.score,
      evidenceLevel: assessment.score === null
        ? "insufficient"
        : assessment.score >= 80
          ? "direct"
          : assessment.score >= 65
            ? "transferable"
            : "foundational",
      evidenceSources: assessment.experienceEvidence ? [assessment.experienceEvidence] : [],
      weight: assessment.weight,
      jdMatchBasis: assessment.jdMatchBasis,
      experienceEvidence: assessment.experienceEvidence,
    };
  });
}

export const mockReports: ReportData[] = [
  {
    id: "international-dispute-lawyer",
    analysisId: "demo-international-dispute-lawyer",
    sessionId: "demo-session",
    source: "mock",
    promptVersion: "demo",
    productVersion: "0.3.0",
    modelVersion: "mock",
    analyzedAt: "2026-08-10T00:00:00.000Z",
    analysisContext: { purpose: "internship_search", educationStage: "law_master", careerScene: "law_firm", practiceAreas: ["dispute_resolution", "international_cross_border"], focusAreas: ["matching", "interview"] },
    targetRole: "涉外争议解决律师",
    status: "AI 分析完成",
    generatedAt: "2026.08.10",
    overallScore: 81,
    summary:
      "岗位核心是中英文法律研究、跨境争议分析与高质量书面交付。你的研究能力具有明显优势，下一步应集中补充英文法律写作与国际仲裁程序经验。",
    jobClassification: {
      careerTrack: "律所与律师业务",
      practiceAreaCategory: "涉外商事",
      practiceArea: "涉外争议解决",
      roleLevel: "初级",
      confidence: 96,
    },
    generalSkills: createGeneralSkills({
      research: {
        score: 89,
        requiredScore: 92,
        weight: 28,
        jdMatchBasis: "JD 要求独立完成境内外法规、案例和仲裁裁决研究。",
        experienceEvidence: "模拟法庭和专题论文体现了争点拆解、案例检索与论证能力。",
      },
      practice: {
        score: 77,
        requiredScore: 86,
        weight: 24,
        jdMatchBasis: "岗位需要起草案件备忘录、证据清单和争议解决法律文书。",
        experienceEvidence: "具备代理意见和案件材料整理训练，但真实跨境案件交付较少。",
      },
      communication: {
        score: 78,
        requiredScore: 84,
        weight: 16,
        jdMatchBasis: "JD 强调向合伙人汇报研究结论并参与客户会议。",
        experienceEvidence: "模拟法庭证明了观点表达和团队协作能力。",
      },
      international: {
        score: 75,
        requiredScore: 90,
        weight: 22,
        jdMatchBasis: "岗位明确要求英文作为工作语言并能够起草英文法律文件。",
        experienceEvidence: "具备英文法律文献阅读经验，英文写作和跨境沟通证据不足。",
      },
      professionalism: {
        score: 86,
        requiredScore: 88,
        weight: 10,
        jdMatchBasis: "案件节奏快，要求工作细致、按时交付并能够快速学习陌生法域。",
        experienceEvidence: "长期研究项目和竞赛准备体现了持续投入与交付可靠性。",
      },
    }),
    jobSpecificSkills: [
      {
        id: "english-legal-writing",
        name: "英文法律写作",
        description: "使用专业英文撰写研究备忘录、案件邮件和法律意见。",
        score: 78,
        requiredScore: 90,
        weight: 36,
        evidence: "JD 明确要求英文工作语言，并承担英文法律文件起草工作。",
        experienceEvidence: "已有英文文献阅读和课程论文基础，缺少完整英文法律备忘录作品。",
      },
      {
        id: "cross-border-dispute-analysis",
        name: "跨境争议案件分析",
        description: "识别跨境争议中的管辖、法律适用、证据和执行问题。",
        score: 82,
        requiredScore: 88,
        weight: 35,
        evidence: "JD 要求参与跨境商事争议与境外诉讼协调。",
        experienceEvidence: "模拟法庭经历可迁移至争点分析，但跨法域分析深度仍需加强。",
      },
      {
        id: "international-arbitration",
        name: "国际仲裁程序理解",
        description: "理解主要仲裁规则、程序节点及裁决承认与执行。",
        score: 70,
        requiredScore: 85,
        weight: 29,
        evidence: "JD 提及参与国际商事仲裁案件及仲裁程序管理。",
        experienceEvidence: "已完成国际仲裁课程学习，尚缺实际程序文件和案件支持经历。",
      },
    ],
    jobRequirements: [
      {
        id: "intl-law-degree",
        category: "hard_requirement",
        name: "法学专业背景",
        description: "具备系统法律教育背景。",
        importance: "high",
        jdEvidence: "法学本科及以上学历。",
      },
      {
        id: "intl-english",
        category: "soft_requirement",
        name: "英文工作能力",
        description: "能够使用英文完成法律研究和书面工作。",
        importance: "high",
        jdEvidence: "英语可作为工作语言，能够起草英文法律文件。",
      },
      {
        id: "intl-research",
        category: "soft_requirement",
        name: "跨法域法律研究",
        description: "检索和比较不同法域的规则与案例。",
        importance: "high",
        jdEvidence: "独立完成境内外法规、案例及仲裁裁决研究。",
      },
      {
        id: "intl-arbitration",
        category: "soft_requirement",
        name: "国际仲裁程序",
        description: "理解国际商事仲裁程序与主要机构规则。",
        importance: "medium",
        jdEvidence: "参与国际商事仲裁案件及程序管理。",
      },
      {
        id: "intl-collaboration",
        category: "soft_requirement",
        name: "团队交付与沟通",
        description: "准确汇报研究结论并支持团队案件交付。",
        importance: "medium",
        jdEvidence: "与合伙人及团队成员高效协作，按时完成工作。",
      },
    ],
    resumeEvidenceMatches: [
      {
        id: "intl-match-degree",
        requirementId: "intl-law-degree",
        requirementName: "法学专业背景",
        status: "met",
        resumeEvidence: ["法学本科在读"],
        sourceType: "education",
        analysis: "简历中的法学教育背景直接对应 JD 的专业要求，硬性条件证据较充分。",
        interviewValue: "low",
      },
      {
        id: "intl-match-english",
        requirementId: "intl-english",
        requirementName: "英文工作能力",
        status: "partial",
        resumeEvidence: ["CET-6", "英文法律文献阅读经历"],
        sourceType: "language",
        analysis: "现有证据能够说明英文阅读基础，但尚未充分证明英文法律写作和实际工作沟通。",
        interviewValue: "high",
      },
      {
        id: "intl-match-research",
        requirementId: "intl-research",
        requirementName: "跨法域法律研究",
        status: "met",
        resumeEvidence: ["跨境数据流动专题研究", "国际商事模拟法庭"],
        sourceType: "project",
        analysis: "研究和比赛经历均包含跨法域资料检索与规则比较，证据较充分。",
        interviewValue: "high",
      },
      {
        id: "intl-match-arbitration",
        requirementId: "intl-arbitration",
        requirementName: "国际仲裁程序",
        status: "not_evidenced",
        resumeEvidence: ["国际仲裁课程"],
        sourceType: "education",
        analysis: "课程经历说明接触过相关知识，但当前简历未说明掌握的规则、程序或具体产出。",
        interviewValue: "medium",
      },
      {
        id: "intl-match-collaboration",
        requirementId: "intl-collaboration",
        requirementName: "团队交付与沟通",
        status: "partial",
        resumeEvidence: ["模拟法庭团队协作"],
        sourceType: "competition",
        analysis: "竞赛团队经历可作为协作证据，但与真实案件节奏和工作汇报仍有差异。",
        interviewValue: "medium",
      },
    ],
    resumeRewriteSuggestions: [
      {
        id: "intl-rewrite-research",
        targetRequirement: "跨法域法律研究",
        originalText: "参与国际商事模拟法庭资料准备。",
        issue: "too_generic",
        suggestedText: "围绕[具体争议问题]检索[涉及法域]的法规与案例，比较[核心规则差异]，形成[具体材料]供团队书状准备使用。",
        reason: "原文没有说明检索对象、法律问题和工作产出，需要用户补充事实后再形成最终版本。",
        needsUserConfirmation: true,
        missingFacts: ["具体争议问题", "涉及法域", "检索材料数量或范围", "最终形成的材料", "材料用途"],
      },
    ],
    experienceMatches: [
      {
        id: "moot-court",
        requiredSkill: "跨境争议案件分析",
        experience: "国际商事模拟法庭",
        evidence: "负责管辖争议、法律适用与案例检索，并参与英文书状资料准备。",
        reasoning: "经历覆盖争点识别、跨法域检索和团队论证，与涉外争议解决的基础工作链路一致。",
        score: 86,
      },
      {
        id: "legal-research",
        requiredSkill: "法律研究与分析",
        experience: "跨境数据流动专题研究",
        evidence: "比较欧盟与中国监管规则并形成 10,000 字研究报告。",
        reasoning: "比较法研究证明了处理不同法域规则和复杂监管材料的能力。",
        score: 88,
      },
      {
        id: "english-reading",
        requiredSkill: "英文法律文件处理",
        experience: "英文法律课程与文献阅读",
        evidence: "持续阅读英文判例、法规与学术文章并完成课程展示。",
        reasoning: "能够支持英文检索和阅读，但与岗位要求的英文写作仍存在能力距离。",
        score: 74,
      },
    ],
    gapAnalysis: {
      strengths: ["法律研究结构清晰", "跨法域检索基础良好", "争议问题敏感度较高"],
      improvements: ["英文法律写作", "国际仲裁程序", "真实案件交付"],
      advice: "优先准备一份英文法律研究备忘录，并用案例说明你如何处理管辖、法律适用和证据问题。",
      answerKeywords: ["跨法域检索", "争点拆解", "英文备忘录", "程序意识"],
    },
    interviewQuestions: [
      interviewQuestion("intl-q1", "resume_deep_dive", "high", "请具体介绍你在国际商事模拟法庭中承担的工作。", ["实际参与程度", "跨法域检索", "团队交付"], "国际商事模拟法庭", ["你检索了哪些法律问题？", "哪一部分由你独立完成？", "最终形成了什么材料？"]),
      interviewQuestion("intl-q2", "resume_deep_dive", "high", "跨境数据流动专题研究中，你如何确定比较法研究范围？", ["研究框架", "信源判断", "结论可靠性"], "跨境数据流动专题研究", ["为什么选择这些法域？", "如何处理规则冲突？", "研究报告供谁使用？"]),
      interviewQuestion("intl-q3", "jd_professional", "high", "面对一项跨境商事争议，你会如何建立初步分析框架？", ["管辖", "法律适用", "证据与执行"], "国际商事模拟法庭或其他真实争议分析经历", ["先核验哪些基础事实？", "如何安排检索顺序？", "哪些风险需要优先提示？"]),
      interviewQuestion("intl-q4", "scenario", "high", "客户提供的事实和文件不完整，但期限临近，你会如何推进研究？", ["事实核验", "优先级管理", "风险沟通"], "能够证明时间压力下完成法律研究的真实经历", ["你会先向谁确认？", "如何标注分析假设？", "如何控制结论边界？"]),
      interviewQuestion("intl-q5", "language", "high", "Please describe an experience in which you used English for legal research or written work.", ["英文法律阅读", "英文写作", "工作准确性"], "英文法律课程、模拟法庭或真实英文研究经历", ["使用了哪些英文信源？", "形成了什么英文成果？", "如何进行语言和法律复核？"]),
      interviewQuestion("intl-q6", "jd_professional", "研究陌生法域法律问题时，你如何保证信息完整性和结论可靠性？", ["检索路径", "权威信源", "交叉验证"], "跨法域专题研究", ["如何确定检索词？", "如何处理二手资料？", "无法确认时如何呈现？"]),
      interviewQuestion("intl-q7", "motivation_fit", "为什么希望从事涉外争议解决，而不是其他法律业务？", ["岗位理解", "动机真实性", "职业匹配"], "能够体现涉外法律兴趣形成过程的真实经历", ["哪段经历最影响你的选择？", "你理解的初级岗位日常是什么？", "当前最需要补足什么？"]),
      interviewQuestion("intl-q8", "scenario", "团队对一项境外规则的理解存在分歧时，你会如何验证并汇报？", ["法律论证", "协作沟通", "结论表达"], "模拟法庭或研究团队中的真实分歧处理经历", ["你会采用哪些信源？", "如何呈现不同观点？", "最终如何形成可用结论？"]),
    ],
    actionPlan: [
      {
        id: "intl-action-research",
        type: "resume_expression",
        title: "补全跨法域研究的工作链路",
        priority: "high",
        requirementId: "intl-research",
        targetRequirement: "跨法域法律研究",
        currentEvidence: "简历写明参与模拟法庭资料准备，但未体现检索问题、规则比较和产出。",
        whyPriority: "这是 JD 高优先要求，也是现有经历中最直接的岗位证据。",
        action: "核验并补充争议问题、涉及法域、个人检索动作、形成材料及其用途。",
      },
      {
        id: "intl-action-english",
        type: "interview_preparation",
        title: "准备英文工作能力核验材料",
        priority: "high",
        requirementId: "intl-english",
        targetRequirement: "英文工作能力",
        currentEvidence: "已有 CET-6 和英文文献阅读经历，英文法律写作证据仍不充分。",
        whyPriority: "JD 明确要求英文书面工作，面试中很可能进一步验证。",
        action: "整理一段真实英文研究经历，准备说明使用的英文信源、个人产出、复核方法和成果用途。",
      },
      {
        id: "intl-action-arbitration",
        type: "evidence_improvement",
        title: "补充仲裁程序课程产出",
        priority: "medium",
        requirementId: "intl-arbitration",
        targetRequirement: "国际仲裁程序",
        currentEvidence: "简历仅列出国际仲裁课程，未说明掌握内容或课程产出。",
        whyPriority: "补充已有课程中的真实成果可以在短期内提高证据清晰度。",
        action: "确认课程中实际完成的案例分析、程序图或书面作业，并将真实产出补入简历。",
      },
    ],
  },
  {
    id: "corporate-ip-counsel",
    analysisId: "demo-corporate-ip-counsel",
    sessionId: "demo-session",
    source: "mock",
    promptVersion: "demo",
    productVersion: "0.3.0",
    modelVersion: "mock",
    analyzedAt: "2026-08-10T00:00:00.000Z",
    analysisContext: { purpose: "campus_recruitment", educationStage: "law_master", careerScene: "in_house", practiceAreas: ["intellectual_property"], focusAreas: ["resume", "matching", "interview"] },
    targetRole: "企业知识产权法务",
    status: "AI 分析完成",
    generatedAt: "2026.08.10",
    overallScore: 84,
    summary:
      "你的知识产权研究经历与岗位专业方向高度一致。主要提升空间在于将学术分析转化为企业知识产权风险管理、权利运营和跨部门协作方案。",
    jobClassification: {
      careerTrack: "企业法务与合规",
      practiceAreaCategory: "知识产权与品牌保护",
      practiceArea: "知识产权法务",
      roleLevel: "初级",
      confidence: 98,
    },
    generalSkills: createGeneralSkills({
      research: {
        score: 84,
        requiredScore: 84,
        weight: 20,
        jdMatchBasis: "JD 要求跟踪知识产权法规、研究侵权风险并形成分析意见。",
        experienceEvidence: "知识产权专题论文证明了法规检索、案例研究和法律论证能力。",
      },
      practice: {
        score: 76,
        requiredScore: 84,
        weight: 24,
        jdMatchBasis: "岗位涉及权利文件审核、侵权材料整理和外部代理事项管理。",
        experienceEvidence: "具备文书与案件材料训练，但企业 IP 实务交付经验仍有限。",
      },
      communication: {
        score: 75,
        requiredScore: 83,
        weight: 20,
        jdMatchBasis: "需要与品牌、研发、产品和外部代理机构持续沟通。",
        experienceEvidence: "模拟法庭体现观点表达和团队协作，跨职能沟通案例需补充。",
      },
      international: {
        score: 72,
        requiredScore: 74,
        weight: 12,
        jdMatchBasis: "岗位需要阅读英文权利文件并支持部分海外品牌保护事项。",
        experienceEvidence: "英文法律文献阅读能力能够支持基础文件处理。",
      },
      professionalism: {
        score: 86,
        requiredScore: 86,
        weight: 24,
        jdMatchBasis: "知识产权事务数量多、节点明确，强调细致记录和主动推进。",
        experienceEvidence: "长期研究项目体现持续跟进、材料管理和按期交付能力。",
      },
    }),
    jobSpecificSkills: [
      {
        id: "ip-risk-management",
        name: "知识产权风险管理",
        description: "识别产品、品牌与内容业务中的知识产权风险并提出处置方案。",
        score: 85,
        requiredScore: 88,
        weight: 40,
        evidence: "JD 要求处理专利、商标、著作权风险及日常咨询。",
        experienceEvidence: "平台经济商标保护研究对应商标与内容侵权风险识别要求。",
      },
      {
        id: "ip-portfolio",
        name: "知识产权组合管理",
        description: "支持商标、专利与版权的申请、维护和价值管理。",
        score: 72,
        requiredScore: 82,
        weight: 30,
        evidence: "JD 要求维护企业权利台账并协调申请、续展与许可事项。",
        experienceEvidence: "了解权利取得规则，但缺少企业权利组合和代理机构管理经验。",
      },
      {
        id: "infringement-response",
        name: "侵权监测与处置",
        description: "完成侵权线索判断、证据整理及投诉或争议处置支持。",
        score: 80,
        requiredScore: 84,
        weight: 30,
        evidence: "JD 明确要求开展侵权监测并支持投诉、诉讼和平台治理。",
        experienceEvidence: "案例研究经历能够迁移至侵权判断和证据链分析。",
      },
    ],
    jobRequirements: [
      {
        id: "ip-law-background",
        category: "hard_requirement",
        name: "法学专业背景",
        description: "具备系统法律教育背景。",
        importance: "high",
        jdEvidence: "法学本科及以上学历，知识产权方向优先。",
      },
      {
        id: "ip-qualification",
        category: "hard_requirement",
        name: "法律职业资格",
        description: "通过国家统一法律职业资格考试。",
        importance: "high",
        jdEvidence: "通过国家统一法律职业资格考试。",
      },
      {
        id: "ip-cet6",
        category: "hard_requirement",
        name: "英语六级或同等资质",
        description: "具备 JD 明确要求的标准化语言资质。",
        importance: "medium",
        jdEvidence: "大学英语六级 500 分以上或同等英语水平。",
      },
      {
        id: "ip-english-work",
        category: "soft_requirement",
        name: "英文法律文件处理",
        description: "能够阅读并处理英文权利文件和法律资料。",
        importance: "medium",
        jdEvidence: "能够阅读英文商标、版权及许可文件。",
      },
      {
        id: "ip-contract-review",
        category: "soft_requirement",
        name: "知识产权合同审核",
        description: "识别许可、合作及内容合同中的知识产权风险。",
        importance: "high",
        jdEvidence: "负责知识产权许可、品牌合作和内容业务协议审核。",
      },
      {
        id: "ip-risk-management",
        category: "soft_requirement",
        name: "知识产权风险管理",
        description: "识别并处理商标、版权及相关侵权风险。",
        importance: "high",
        jdEvidence: "处理专利、商标、著作权风险及日常咨询。",
      },
      {
        id: "ip-cross-team",
        category: "soft_requirement",
        name: "跨部门沟通",
        description: "与品牌、产品、研发及外部机构协作推动事项落地。",
        importance: "medium",
        jdEvidence: "协同品牌、产品和外部代理机构推进知识产权项目。",
      },
    ],
    resumeEvidenceMatches: [
      {
        id: "ip-match-background",
        requirementId: "ip-law-background",
        requirementName: "法学专业背景",
        status: "met",
        resumeEvidence: ["法学本科在读", "知识产权法专题课程"],
        sourceType: "education",
        analysis: "法学教育背景直接满足专业要求，知识产权课程进一步增强了方向相关性。",
        interviewValue: "low",
      },
      {
        id: "ip-match-qualification",
        requirementId: "ip-qualification",
        requirementName: "法律职业资格",
        status: "not_evidenced",
        resumeEvidence: ["简历写有‘法考备考’但未说明是否通过"],
        sourceType: "qualification",
        analysis: "当前信息不足以核验是否满足硬性条件，需要用户确认考试结果和取得时间。",
        interviewValue: "low",
      },
      {
        id: "ip-match-cet6",
        requirementId: "ip-cet6",
        requirementName: "英语六级或同等资质",
        status: "met",
        resumeEvidence: ["CET-6 532 分"],
        sourceType: "language",
        analysis: "简历已给出可核验的标准化英语成绩，满足 JD 明确门槛。",
        interviewValue: "low",
      },
      {
        id: "ip-match-english-work",
        requirementId: "ip-english-work",
        requirementName: "英文法律文件处理",
        status: "partial",
        resumeEvidence: ["CET-6 532 分", "阅读英文知识产权论文"],
        sourceType: "language",
        analysis: "标准化成绩和论文阅读说明英文基础，但尚未证明处理英文合同、权利文件或法律写作的实际经历。",
        interviewValue: "medium",
      },
      {
        id: "ip-match-contract",
        requirementId: "ip-contract-review",
        requirementName: "知识产权合同审核",
        status: "partial",
        resumeEvidence: ["合同审查课程中完成服务合同条款分析"],
        sourceType: "project",
        analysis: "已有合同审查训练，但合同类型并非知识产权许可或品牌合作，证据只能部分对应。",
        interviewValue: "high",
      },
      {
        id: "ip-match-risk",
        requirementId: "ip-risk-management",
        requirementName: "知识产权风险管理",
        status: "met",
        resumeEvidence: ["平台经济商标保护研究", "知识产权案例分析项目"],
        sourceType: "project",
        analysis: "研究经历直接覆盖商标侵权责任、平台治理与案例比较，能够充分证明风险识别和法律分析基础。",
        interviewValue: "high",
      },
      {
        id: "ip-match-cross-team",
        requirementId: "ip-cross-team",
        requirementName: "跨部门沟通",
        status: "not_evidenced",
        resumeEvidence: [],
        sourceType: "campus",
        analysis: "当前简历中未找到足以证明与品牌、产品或外部机构协作的具体经历；这不代表用户不具备该能力。",
        interviewValue: "medium",
      },
    ],
    resumeRewriteSuggestions: [
      {
        id: "ip-rewrite-case-material",
        targetRequirement: "知识产权风险管理",
        originalText: "协助整理知识产权案件材料。",
        issue: "too_generic",
        suggestedText: "围绕[案件类型]整理[材料范围]，完成[具体动作]并形成[具体产出]，供[使用对象与用途]使用。",
        reason: "原文只有辅助性动词，没有说明处理对象、法律问题、个人动作与交付结果，不能直接改写成更高职责。",
        needsUserConfirmation: true,
        missingFacts: ["案件类型", "案件或材料数量", "是否进行案例检索", "是否提炼争议焦点", "最终形成什么材料", "材料供谁使用"],
      },
      {
        id: "ip-rewrite-contract",
        targetRequirement: "知识产权合同审核",
        originalText: "参与合同审核工作。",
        issue: "missing_scope",
        suggestedText: "审核[合同类型与数量]中的[重点条款]，识别[具体风险]并形成[修改意见或风险清单]。",
        reason: "需要确认合同类型、审查范围和实际产出，避免把课程练习或辅助工作表述为独立负责。",
        needsUserConfirmation: true,
        missingFacts: ["合同类型", "合同数量", "实际审查的条款", "识别的风险", "是否形成修改意见"],
      },
      {
        id: "ip-rewrite-research",
        targetRequirement: "知识产权风险管理",
        originalText: "围绕平台经济商标保护完成专题研究，形成12,000字研究报告。",
        issue: "missing_output",
        suggestedText: "围绕平台经济中的商标侵权责任开展专题研究，检索法规及代表性案例，比较平台治理规则与裁判观点，形成12,000字研究报告。",
        reason: "原文已有可核验的研究主题和字数，补充已有的研究动作后可更清晰地对应岗位风险分析要求。",
        needsUserConfirmation: false,
      },
    ],
    experienceMatches: [
      {
        id: "ip-research",
        requiredSkill: "知识产权风险管理",
        experience: "平台经济商标保护研究",
        evidence: "围绕平台商标侵权责任完成专题研究并形成 12,000 字报告。",
        reasoning: "研究主题直接对应岗位中的商标保护与平台侵权治理要求。",
        score: 90,
      },
      {
        id: "case-analysis",
        requiredSkill: "侵权监测与处置",
        experience: "知识产权案例分析项目",
        evidence: "完成侵权构成、抗辩理由与损害赔偿判例比较。",
        reasoning: "案例分析证明了侵权线索判断、规则适用和证据关注能力。",
        score: 86,
      },
      {
        id: "policy-research",
        requiredSkill: "行业与政策跟踪",
        experience: "数字内容行业政策研究",
        evidence: "持续跟踪平台与数字内容监管动态并完成影响简报。",
        reasoning: "能够将法律规则放入业务环境理解，适合支持产品风险评估。",
        score: 80,
      },
    ],
    gapAnalysis: {
      strengths: ["知识产权方向明确", "侵权案例分析扎实", "法规研究能力突出"],
      improvements: ["权利组合管理", "业务沟通", "企业 IP 流程经验"],
      advice: "面试表达中应从企业资产保护和业务连续性出发，说明法律判断如何转化为风险分级与处置方案。",
      answerKeywords: ["资产保护", "风险分级", "处置路径", "跨部门协作"],
    },
    interviewQuestions: [
      interviewQuestion("ip-q1", "resume_deep_dive", "high", "请具体介绍平台经济商标保护研究中你完成的工作。", ["法律检索", "侵权分析", "个人产出"], "平台经济商标保护研究", ["你研究的核心问题是什么？", "使用了哪些规则或案例？", "12,000 字报告最终如何使用？"]),
      interviewQuestion("ip-q2", "resume_deep_dive", "high", "知识产权案例分析项目中，你如何判断侵权构成与抗辩理由？", ["要件分析", "案例比较", "证据意识"], "知识产权案例分析项目", ["你选择了哪些代表性案例？", "争议焦点如何提炼？", "哪一部分由你独立完成？"]),
      interviewQuestion("ip-q3", "jd_professional", "你如何理解企业知识产权管理与业务竞争力之间的关系？", ["企业视角", "资产保护", "业务连续性"], "平台商标保护研究或其他真实知识产权经历", ["哪些风险应优先管理？", "如何衡量处置成本？", "法务如何支持业务目标？"]),
      interviewQuestion("ip-q4", "scenario", "发现线上平台存在疑似商标侵权时，你会如何推进处理？", ["侵权判断", "证据固定", "处置路径"], "知识产权案例分析项目", ["首先保存哪些证据？", "如何判断投诉或诉讼路径？", "何时需要外部律师支持？"]),
      interviewQuestion("ip-q5", "jd_professional", "审核品牌合作协议时，你会重点关注哪些知识产权条款？", ["权利归属", "许可范围", "违约与处置"], "合同审查课程中的真实条款分析经历", ["如何界定使用场景？", "如何处理第三方素材？", "发现权利瑕疵时如何建议？"]),
      interviewQuestion("ip-q6", "scenario", "业务团队认为知识产权审核影响上线速度时，你会如何沟通？", ["风险分级", "替代方案", "跨部门协作"], "能够证明团队沟通和推进的真实项目经历", ["哪些风险不能让步？", "如何提出可选方案？", "如何记录风险接受决定？"]),
      interviewQuestion("ip-q7", "motivation_fit", "为什么希望从事企业知识产权法务，而不是知识产权诉讼或代理？", ["岗位理解", "企业视角", "动机真实性"], "知识产权方向形成过程中的真实研究或实践经历", ["你如何理解企业法务的工作对象？", "最感兴趣的 IP 业务环节是什么？", "现有经历如何迁移？"]),
      interviewQuestion("ip-q8", "language", "If you had to review an English licence agreement, how would you ensure accurate understanding and identify key risks?", ["英文法律阅读", "条款识别", "复核意识"], "英文知识产权论文阅读或其他真实英文材料处理经历", ["遇到陌生术语如何处理？", "哪些条款会优先核验？", "如何记录不确定结论？"]),
    ],
    actionPlan: [
      {
        id: "ip-action-research",
        type: "resume_expression",
        title: "突出商标研究的风险判断价值",
        priority: "high",
        requirementId: "ip-risk-management",
        targetRequirement: "知识产权风险管理",
        currentEvidence: "已有平台商标保护研究和 12,000 字报告，但简历未完整体现检索、比较与风险结论。",
        whyPriority: "这是当前最强的岗位专项证据，补全表达可直接提高简历相关性。",
        action: "在不新增事实的前提下补充研究对象、使用的法规案例、比较动作和报告用途。",
      },
      {
        id: "ip-action-contract",
        type: "interview_preparation",
        title: "准备合同审查经历的事实边界",
        priority: "high",
        requirementId: "ip-contract-review",
        targetRequirement: "知识产权合同审核",
        currentEvidence: "仅有服务合同课程项目，尚未证明知识产权许可或品牌合作合同经验。",
        whyPriority: "合同审核是 JD 高优先要求，面试官很可能核验合同类型和实际参与程度。",
        action: "整理真实审查条款、识别风险、修改建议和课程场景，明确说明其与知识产权合同的差异。",
      },
      {
        id: "ip-action-english",
        type: "evidence_improvement",
        title: "补充英文材料实际使用证据",
        priority: "medium",
        requirementId: "ip-english-work",
        targetRequirement: "英文法律文件处理",
        currentEvidence: "CET-6 和英文论文阅读能够证明基础，但未体现法律文件处理。",
        whyPriority: "可通过梳理已有课程或研究中的真实英文材料快速补强，而无需虚构工作经历。",
        action: "确认曾实际阅读的英文权利文件、案例或论文，并写清阅读目的、提取信息和产出。",
      },
    ],
  },
  {
    id: "general-compliance-counsel",
    analysisId: "demo-general-compliance-counsel",
    sessionId: "demo-session",
    source: "mock",
    promptVersion: "demo",
    productVersion: "0.3.0",
    modelVersion: "mock",
    analyzedAt: "2026-08-10T00:00:00.000Z",
    analysisContext: { purpose: "campus_recruitment", educationStage: "law_undergraduate", careerScene: "compliance", practiceAreas: ["corporate_commercial"], focusAreas: ["matching", "planning"] },
    targetRole: "综合法务与合规专员",
    status: "AI 分析完成",
    generatedAt: "2026.08.10",
    overallScore: 78,
    summary:
      "岗位重心是合同支持、合规风险识别与业务协作。你的法律研究基础可靠，但需要通过合同审核和业务风险案例证明实务执行能力。",
    jobClassification: {
      careerTrack: "企业法务与合规",
      practiceAreaCategory: "综合法务与合规",
      practiceArea: "综合法务",
      roleLevel: "初级",
      confidence: 95,
    },
    generalSkills: createGeneralSkills({
      research: {
        score: 80,
        requiredScore: 80,
        weight: 14,
        jdMatchBasis: "JD 要求检索业务相关法规并支持合规政策解读。",
        experienceEvidence: "政策研究经历能够证明法规检索和影响分析能力。",
      },
      practice: {
        score: 70,
        requiredScore: 88,
        weight: 30,
        jdMatchBasis: "岗位主要工作包括合同审核、法律咨询和制度文件起草。",
        experienceEvidence: "具备法律文书基础，缺少高频合同审核和真实业务支持经验。",
      },
      communication: {
        score: 74,
        requiredScore: 86,
        weight: 24,
        jdMatchBasis: "需要与销售、采购和产品团队沟通并推动风险方案落地。",
        experienceEvidence: "团队项目体现协作基础，跨部门业务沟通证据不足。",
      },
      international: {
        score: 65,
        requiredScore: 65,
        weight: 7,
        jdMatchBasis: "英文能力为加分项，仅部分合同和资料涉及英文。",
        experienceEvidence: "英文法律文件阅读能够满足基础资料处理。",
      },
      professionalism: {
        score: 87,
        requiredScore: 88,
        weight: 25,
        jdMatchBasis: "岗位事项并行度高，强调责任意识、细致程度和主动跟进。",
        experienceEvidence: "研究项目与竞赛经历体现计划管理和稳定交付能力。",
      },
    }),
    jobSpecificSkills: [
      {
        id: "contract-review",
        name: "商业合同审核",
        description: "识别合同中的权责、付款、违约、终止与争议风险。",
        score: 68,
        requiredScore: 88,
        weight: 42,
        evidence: "JD 将销售、采购和合作协议审核列为日常核心职责。",
        experienceEvidence: "完成合同法课程训练，但缺少真实商业合同审核成果。",
      },
      {
        id: "compliance-risk",
        name: "合规风险识别",
        description: "识别业务活动中的监管、流程和操作合规风险。",
        score: 80,
        requiredScore: 84,
        weight: 32,
        evidence: "JD 要求跟踪监管政策并支持内部合规检查。",
        experienceEvidence: "互联网行业政策研究能够证明监管跟踪和影响判断能力。",
      },
      {
        id: "business-solution",
        name: "业务法律方案设计",
        description: "在业务目标与风险边界之间形成可执行建议。",
        score: 66,
        requiredScore: 86,
        weight: 26,
        evidence: "JD 强调响应业务咨询并提供可落地的解决方案。",
        experienceEvidence: "现有经历以学术分析为主，商业权衡和方案落地证据较弱。",
      },
    ],
    jobRequirements: [
      {
        id: "compliance-degree",
        category: "hard_requirement",
        name: "法学专业背景",
        description: "具备法律专业教育背景。",
        importance: "high",
        jdEvidence: "法学本科及以上学历。",
      },
      {
        id: "compliance-contract",
        category: "soft_requirement",
        name: "商业合同审核",
        description: "识别商业合同中的权责和履约风险。",
        importance: "high",
        jdEvidence: "负责销售、采购和合作协议审核。",
      },
      {
        id: "compliance-policy",
        category: "soft_requirement",
        name: "合规政策分析",
        description: "跟踪监管变化并评估业务影响。",
        importance: "high",
        jdEvidence: "持续跟踪监管政策并支持内部合规检查。",
      },
      {
        id: "compliance-english",
        category: "preferred_requirement",
        name: "英文法律文件阅读",
        description: "能够阅读基础英文合同与法律资料。",
        importance: "low",
        jdEvidence: "具备英文法律文件阅读能力者优先。",
      },
      {
        id: "compliance-communication",
        category: "soft_requirement",
        name: "业务沟通与推进",
        description: "与业务团队沟通风险并推动方案落地。",
        importance: "high",
        jdEvidence: "与销售、采购和产品团队协作处理法律事项。",
      },
    ],
    resumeEvidenceMatches: [
      {
        id: "compliance-match-degree",
        requirementId: "compliance-degree",
        requirementName: "法学专业背景",
        status: "met",
        resumeEvidence: ["法学本科在读"],
        sourceType: "education",
        analysis: "法学教育背景直接满足 JD 的专业门槛。",
        interviewValue: "low",
      },
      {
        id: "compliance-match-contract",
        requirementId: "compliance-contract",
        requirementName: "商业合同审核",
        status: "partial",
        resumeEvidence: ["合同审查课程项目"],
        sourceType: "project",
        analysis: "当前只有课程项目证据，能够证明基础审查逻辑，但尚未体现真实商业场景。",
        interviewValue: "high",
      },
      {
        id: "compliance-match-policy",
        requirementId: "compliance-policy",
        requirementName: "合规政策分析",
        status: "met",
        resumeEvidence: ["互联网监管政策简报"],
        sourceType: "project",
        analysis: "政策跟踪和影响简报直接对应监管识别与业务影响分析要求。",
        interviewValue: "high",
      },
      {
        id: "compliance-match-english",
        requirementId: "compliance-english",
        requirementName: "英文法律文件阅读",
        status: "not_evidenced",
        resumeEvidence: ["CET-6"],
        sourceType: "language",
        analysis: "语言成绩能够证明基础，但简历未说明英文法律文件实际使用经历。",
        interviewValue: "low",
      },
      {
        id: "compliance-match-communication",
        requirementId: "compliance-communication",
        requirementName: "业务沟通与推进",
        status: "partial",
        resumeEvidence: ["法律创新竞赛团队项目"],
        sourceType: "competition",
        analysis: "团队项目可补充协作证据，但与企业跨部门业务沟通的场景仍有差异。",
        interviewValue: "medium",
      },
    ],
    resumeRewriteSuggestions: [
      {
        id: "compliance-rewrite-contract",
        targetRequirement: "商业合同审核",
        originalText: "参与合同审查课程项目。",
        issue: "missing_output",
        suggestedText: "审查[合同类型]中的[具体条款]，识别[风险类型]并形成[修改建议或审查清单]。",
        reason: "需要补充实际审查范围和产出，才能判断课程项目与岗位合同工作的相关程度。",
        needsUserConfirmation: true,
        missingFacts: ["合同类型", "审查条款", "识别风险", "最终产出"],
      },
    ],
    experienceMatches: [
      {
        id: "policy-brief",
        requiredSkill: "合规风险识别",
        experience: "互联网监管政策简报",
        evidence: "跟踪平台治理规则并分析对企业产品流程的影响。",
        reasoning: "经历能够迁移到监管动态跟踪、风险识别和内部提示工作。",
        score: 84,
      },
      {
        id: "contract-course",
        requiredSkill: "商业合同审核",
        experience: "合同审查课程项目",
        evidence: "完成服务合同条款审查并提出违约责任和终止条款修改建议。",
        reasoning: "具备基础审查逻辑，但项目复杂度和真实业务约束有限。",
        score: 72,
      },
      {
        id: "team-project",
        requiredSkill: "业务沟通与协作",
        experience: "法律创新竞赛团队项目",
        evidence: "协调研究、产品展示和答辩分工并按期完成交付。",
        reasoning: "证明了协作与项目推进能力，但仍需转化为跨部门业务沟通表达。",
        score: 76,
      },
    ],
    gapAnalysis: {
      strengths: ["法规研究基础可靠", "学习与执行稳定", "合规敏感度良好"],
      improvements: ["商业合同审核", "业务方案设计", "跨部门沟通"],
      advice: "优先通过真实合同案例展示条款风险判断，并将建议表达为业务可选择的方案，而非单一法律结论。",
      answerKeywords: ["合同目的", "风险等级", "可选方案", "业务协同"],
    },
    interviewQuestions: [
      interviewQuestion("compliance-q1", "resume_deep_dive", "high", "请具体介绍合同审查课程项目中你完成的工作。", ["实际参与程度", "条款分析", "工作产出"], "合同审查课程项目", ["审查的是什么合同？", "发现了哪些具体风险？", "最终形成了什么材料？"]),
      interviewQuestion("compliance-q2", "resume_deep_dive", "high", "互联网监管政策简报中，你如何判断规则对业务流程的影响？", ["政策检索", "影响分析", "结论表达"], "互联网监管政策简报", ["跟踪了哪些监管来源？", "如何筛选与业务相关的变化？", "简报供谁使用？"]),
      interviewQuestion("compliance-q3", "jd_professional", "审核一份业务合作合同时，你通常会关注哪些核心问题？", ["合同目的", "权责分配", "履约风险"], "合同审查课程项目", ["如何确定审查重点？", "如何处理模糊条款？", "法律风险如何转化为修改意见？"]),
      interviewQuestion("compliance-q4", "scenario", "业务坚持接受一项高风险条款时，你会如何处理？", ["风险分级", "替代方案", "升级机制"], "能够证明沟通和推进的真实项目经历", ["如何说明风险后果？", "可以提供哪些替代方案？", "什么情况下需要升级汇报？"]),
      interviewQuestion("compliance-q5", "jd_professional", "新监管规则发布后，你会如何评估其对公司的影响？", ["监管识别", "业务映射", "落地计划"], "互联网监管政策简报", ["如何确认规则适用范围？", "会访谈哪些业务人员？", "最终输出什么材料？"]),
      interviewQuestion("compliance-q6", "scenario", "销售团队要求当天完成一份重要合同审核，你会如何安排？", ["优先级管理", "信息确认", "风险边界"], "时间压力下完成研究或项目交付的真实经历", ["首先确认哪些信息？", "如何区分必须修改和建议修改？", "如何记录未解决风险？"]),
      interviewQuestion("compliance-q7", "motivation_fit", "为什么希望从事企业综合法务与合规岗位？", ["岗位理解", "业务意识", "职业动机"], "合规兴趣形成过程中的真实课程、研究或项目经历", ["你如何理解法务与业务的关系？", "最希望参与哪类事项？", "现有经历如何迁移？"]),
      interviewQuestion("compliance-q8", "resume_deep_dive", "法律创新竞赛中，你如何协调分工并保证按期交付？", ["协作沟通", "项目推进", "个人贡献"], "法律创新竞赛团队项目", ["你负责的具体部分是什么？", "遇到分歧如何处理？", "最终交付结果是什么？"]),
    ],
    actionPlan: [
      {
        id: "compliance-action-contract",
        type: "resume_expression",
        title: "补全合同审查项目的具体产出",
        priority: "high",
        requirementId: "compliance-contract",
        targetRequirement: "商业合同审核",
        currentEvidence: "简历仅写参与合同审查课程项目，未说明合同类型、条款、风险和产出。",
        whyPriority: "合同审核是 JD 高优先要求，现有经历相关但表达信息不足。",
        action: "核验并补充合同类型、实际审查条款、识别风险和形成的修改建议或清单。",
      },
      {
        id: "compliance-action-policy",
        type: "interview_preparation",
        title: "准备监管政策影响分析追问",
        priority: "high",
        requirementId: "compliance-policy",
        targetRequirement: "合规政策分析",
        currentEvidence: "已有互联网监管政策简报，是简历中与合规岗位最直接的证据。",
        whyPriority: "面试官很可能追问信源、分析方法、业务影响和简报用途。",
        action: "面试前列出监管来源、筛选标准、业务映射过程、个人结论和简报实际用途。",
      },
      {
        id: "compliance-action-communication",
        type: "interview_preparation",
        title: "准备一次真实协作推进经历",
        priority: "medium",
        requirementId: "compliance-communication",
        targetRequirement: "业务沟通与推进",
        currentEvidence: "法律创新竞赛能够证明团队协作，但尚未体现企业跨部门场景。",
        whyPriority: "软性证据不足不阻碍投递，但需要在面试中准确说明可迁移的协作方式。",
        action: "选择一个真实团队项目，准备说明分歧、个人沟通动作、交付节点和最终结果，不包装成企业业务经验。",
      },
    ],
  },
];

// 当前 Demo 默认展示企业知识产权法务案例；切换索引即可验证其他岗位模型。
export const mockReport = mockReports[1];
